name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'go-stock-windows-amd64.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
#          - name: 'go-stock-linux-amd64'
#            platform: 'linux/amd64'
#            os: 'ubuntu-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get commit message
        id: get_commit_message
        run: |
          $commit_message = & git log -1 --pretty=format:"# [%an  %ad] # %s %b"
          echo "::set-output name=commit_message::$commit_message"

      - name: Build wails
        uses: ArvinLovegood/wails-build-action@v2.7
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.23'
          build-tags: ${{ github.ref_name }}
          build-commit-message: ${{ steps.get_commit_message.outputs.commit_message }}
